version: "3.7"
services:

    mysql:
      image: mysql:8.0
      container_name: serwild-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=GornikPzy
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=usersymfony
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: serwild-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: serwild-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

