version: '3.1'

services:
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_PASSWORD: 1234
            MYSQL_USER: root
            MYSQL_DATABASE: wordpress
        volumes:
            - mysql:/var/lib/mysql

    wordpress:
        image: wordpress:5.2-php7.3-apache
        restart: always
        ports:
            - 8000:80
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: 1234
        volumes:
            - wordpress:/var/www/html
            - ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name
        depends_on:
            - mysql

volumes:
    mysql:
    wordpress:
