version: '3.7'
services:

    wp:
        image: wordpress:php7.3-apache
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: "wordpress"
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: "usersymfony"
        ports:
            - "8000:80"

    mysql:
        image: mysql:8.0
        container_name: serwild-wordpress-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=root
            - MYSQL_PASSWORD=usersymfony
        ports:
            - "3306:3306"
