version: '3.7'
services:

    wp:
        build: .
        environment:
            WORDPRESS_DB_PASSWORD: 1234
        ports:
            - "8000:80"

    mysql:
        image: mysql:8.0
        container_name: serwild-wordpress-mysql
        working_dir: /wordpress
        volumes:
            - .:/wordpress
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=root
            - MYSQL_PASSWORD=usersymfony
        ports:
            - "3306:3306"
