version: "3.7"
services:

    webserver:
        image: nginx:alpine
        container_name: serwild-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php-fpm:
        build: .docker/php
        container_name: serwild-php
        working_dir: /application
        volumes:
            - .:/application
            - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        command: composer install --no-interaction --prefer-dist --no-dev --no-ansi
        ports:
            - "9000:9000"
